### ISSUE TITLE
Wrong option passed to the `geometry` package

### ISSUE THREAD

**Issue by dbitouze** [rrthomas/pdfjam#73] opened 2023-11-20 09:57 UTC
Consider the following MCE (`test.tex`):
```latex
\documentclass{article}
\usepackage{blindtext}
\begin{document}
\Blinddocument
\end{document}
```
the compilation of which resulting in a 16 pages PDF (joined) file.

With the current (3.10) version of `pdfjam`, running:
```shell
pdfjam --nup 2x2 --landscape test.pdf
```
fails with the error:

> pdfjam ERROR: Run 1: Output file not written

A glance at the `.tex` temporary file used by `pdfjam` reveals that the problem comes from the option given to the `geometry` package:
```latex
\usepackage[papersize={A4A4,A4A4}]{geometry}
```

[test.pdf](https://github.com/rrthomas/pdfjam/files/13412299/test.pdf)

**Comment by mgkurtz** [comment] 2024-11-05 13:02
Cannot reproduce this with a current `pdfjam` version. Likely fixed by now.

**Closed** 2024-11-07 21:09 UTC
