### ISSUE TITLE
Patch for pdfjam to work under Cygwin

### ISSUE THREAD

**Issue by DavidFirth** [rrthomas/pdfjam#3] opened 2019-11-02 20:24 UTC
Lucas has kindly sent a patch that seems to fix the pipelines problem in Cygwin.

I need to check it and accept the patch if it's all good.

**Comment by DavidFirth** [comment] 2019-11-05 20:22
Now implemented for version 3.00.  Still needs to be tested.

**Comment by Lucas-C** [comment] 2019-11-07 08:05
I just tested it under Cygwin, to concatenate 2 PDF files.

After some debugging I've juste found the error message:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6930 64-bit)
entering extended mode
! I can't find file `/var/tmp/pdfjam-UrCZbm/a.tex'.
<*> /var/tmp/pdfjam-UrCZbm/a.tex

Please type another input file name:
```

I'm now going to try to find a fix

**Comment by Lucas-C** [comment] 2019-11-07 08:11
My bad, I was using an older version of PDFJam !
I thought this link would get me the version of the `master` branch: https://github.com/DavidFirth/pdfjam/raw/master/releases/pdfjam_latest.tgz
But it points to a non-Cygwin-patched version :)

Using the latest version of this repo `master` branch, it all works well !

**Comment by DavidFirth** [comment] 2019-11-07 08:20
Many thanks, Lucas!  Sorry for the confusion about pdfjam_latest.tgz.  I should clarify this somehow --- I will give this some thought.

Anyway, I will now class this Cygwin issue as closed.  If you have other such improvements to suggest, then that would be welcomed.

**Comment by lemniscati** [comment] 2020-05-02 21:49
@Lucas-C the patch using `cygpath -w` makes cygwin's pdfjam fail to work.
Only checking `CYGWIN`  in `uname` and rewriting path cause an issue.

Please, check so that it does not affect on cygwin's pdfjam, even if you use non-cygwin pdflatex.

And I've made a revert pull-request #21 about it.

Thank you.

**Comment by DavidFirth** [comment] 2020-05-05 09:40
Thanks @lemniscati for reporting the problem that you found.  Since I don't use cygwin myself, and since I know nothing about it, I am reliant upon people such as you and @Lucas-C to help me get pdfjam to work under cygwin.  **To @Lucas-C** : can you please confirm that the diagnosis and solution provided by @lemniscati is correct?

**Comment by Lucas-C** [comment] 2020-05-13 12:30
Sadly, my local texlive installation is completly broken and I cannot test this right now :(

**Comment by lemniscati** [comment] 2020-05-13 13:33
Oh...
By the way, @Lucas-C, are you using MikTeX on Windows?

**Comment by DavidFirth** [comment] 2020-05-14 10:15
Thanks, both @lemniscati and @Lucas-C, for further input on this.

As I have no knowledge of either cygwin or MikTeX, I don't plan to make any changes to the package for now.  I would welcome further advice (from others too, if there is interest in this).

**Comment by lemniscati** [comment] 2020-05-14 11:21
Thank you for reopening the issue.

I guess the commit 72d12db07a49f9098e470fc770fe3f6e5036b9d5 is a try for making `pdfjam` work with MiKTeX on Windows through Cygwin.
So, it is a new challenge.

I'm not familar with MiKTeX on Windows.
And, I've tried installing it, and have found that MiKTeX seems to have no shell. 
So, I think MiKTeX on Windows does not support `pdfjam` by itself.

On the other hand, the commit has made `pdfjam` fail to work on Cygwin, although it did work fine formerly.

This is a situation.

**Comment by lemniscati** [comment] 2020-05-14 12:35
I've sent another pull-request #22, which make `pdfjam` work on pure Cygwin and enable the patch by Lucas only when using non-Cygwin LaTeX from Cygwin.

But I've not checked yet if it works when using pdflatex of MiKTeX on Windows from Cygwin.

**Comment by Lucas-C** [comment] 2020-05-14 12:37
I'll give it a try this evening on another computer where I also have Cygwin installed

**Comment by lemniscati** [comment] 2020-05-15 04:08
Please, also, check results of a following code, which is crucial:

`latex=pdflatex; [ x"$(uname -o)" = x"Cygwin" ] && "${latex}" -version | head -1 | grep -qv Cygwin && echo YES || echo NO`

Expected results are:

When invoked on Cygwin environment and using non-Cygwin pdflatex → `YES`.
When invoked on Cygwin environment and using Cygwin pdflatex → `NO`.
When invoked on non-Cygwin environment → `NO`.

**Comment by Lucas-C** [comment] 2020-05-15 08:01
Damn. I can't reproduce this on my other computer, as I'm stuck with an error due to a missing `pdfpages.sty` Latex package. After spending some time trying to fix this issue, the only thing I see that could work would be do a full Cygwin upgrade, which I won't be able to do right now.

@lemniscati I haven't installed MikTeX with a Windows installer, only Cygwin packages using `apt-cyg`.

I had a look at your PR #22 and it looks good to me.

On my computer your one-liner gives me `NO`

**Comment by lemniscati** [comment] 2020-05-15 08:57
If the one-liner gives `NO`, your patch will be disabled in PR #22...
and it is very likely that your using `pdflatex` of Cygwin (not MiKTeX)

Please also check (in order to clarify the situation)

    uname -o
    type -a pdflatex
    type -a kpsewhich

 on your cygwin environment.

By the way, it seems that `apt-cyg` is not a part of Cygwin, since there is no packages in search results: https://cygwin.com/cgi-bin2/package-grep.cgi?grep=apt-cyg&arch=x86_64
I guess unofficial tools may cause some issue...

**Comment by lemniscati** [comment] 2020-05-16 01:20
Updated #22.
Please see https://github.com/DavidFirth/pdfjam/pull/22#issuecomment-629567205
It may also work when using non-Cygwin LaTeX from a Cygwin environment

Need someone to check.

**Comment by lemniscati** [comment] 2020-05-22 13:55
Is there anyone else who would check PR #22?

**Comment by lemniscati** [comment] 2020-08-01 10:03
Hi, @DavidFirth.

The cygwin mainainer of texlive packages has adopted PR #26, which also includes PR #22
(cf. https://sourceware.org/pipermail/cygwin/2020-July/245464.html).

And, it does work on cygwin, now.

Regards,
Lem

**Comment by Lucas-C** [comment] 2020-08-02 18:18
Thanks for your continuous effort on fixing this issue @lemniscati  !
As explained in May, I can't really test this out myself, but your commits seem really fine to me :)

**Comment by rrthomas** [comment] 2021-11-09 12:53
Closing, now the changes from #22 have been merged.

**Closed by rrthomas** 2021-11-09 12:53 UTC
